repos:
- repo: local
  hooks:
  - id: ruff (format)
    name: Format
    entry: poetry run ruff format
    language: system
    types: [python]
    require_serial: true
  - id: ruff (lint)
    name: Lint
    entry: poetry run ruff
    language: system
    types: [python]
    require_serial: true
  - id: pytest
    name: Test
    entry: poetry run pytest tests
    language: system
    types: [python]
    pass_filenames: false
