repos:
- repo: local
  hooks:
  - id: ruff
    name: Linting
    entry: poetry run ruff .
    language: system
    types: [python]
    require_serial: true
- repo: local
  hooks:
  - id: pytest
    name: Tests
    entry: poetry run pytest tests
    language: system
    types: [python]
    pass_filenames: false
